version: 0.1

phases:
  install:
    commands:
      - echo Build started on `date`
      - echo Installing required libs...
      - npm install -g mocha yarn
  build:
    commands:
      - yarn install
  test:
    commands:
      - mocha
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
